In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = np.array([[1.5,2,3],[4,5,6]], dtype = float)

In [4]:
a

array([1, 2, 3])

In [6]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [8]:
arr = np.arange(0,11,2)

In [9]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [10]:
arr= np.zeros((2,3))

In [11]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr = np.ones((4, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
arr = np.linspace(1,2,5)

In [16]:
arr

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
arr = np.random.randint(5,800,5)
arr

array([783, 317,  61, 633, 348])

## Inspecting Numpy Arrays

In [18]:
pip install git

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement git (from versions: none)
ERROR: No matching distribution found for git
